export const PJ_CREATION_START = 'PJ_CREATION_START';
export const PJ_CREATION_SUCCESS = 'PJ_CREATION_SUCCESS';
export const PJ_CREATION_FAIL = 'PJ_CREATION_FAIL';

export const PJ_FETCH_START = 'PJ_FETCH_START';
export const PJ_FETCH_SUCCESS = 'PJ_FETCH_SUCCESS';
export const PJ_FETCH_FAIL = 'PJ_FETCH_FAIL';

export const MONSTER_CREATION_START = 'MONSTER_CREATION_START';
export const MONSTER_CREATION_SUCCESS = 'MONSTER_CREATION_SUCCESS';
export const MONSTER_CREATION_FAIL = 'MONSTER_CREATION_FAIL';

export const MONSTER_FETCH_START = 'MONSTER_FETCH_START';
export const MONSTER_FETCH_SUCCESS = 'MONSTER_FETCH_SUCCESS';
export const MONSTER_FETCH_FAIL = 'MONSTER_FETCH_FAIL';